const paises = [
    {
        nombre_comun: "Bolivia",
        nombre_oficial: "Estado Plurinacional de Bolivia",
        poblacion: 11673021,
        region: "América",
        capital: "Sucre",
        moneda: "Boliviano (BOB)",
        idiomas: ["Español", "Quechua", "Aymara"],
        fronteras: ["ARG", "BRA", "CHL", "PRY", "PER"],
        bandera: "https://flagcdn.com/w320/bo.png",
    },
    {
        nombre_comun: "Argentina",
        nombre_oficial: "República Argentina",
        poblacion: 45376763,
        region: "América",
        capital: "Buenos Aires",
        moneda: "Peso argentino (ARS)",
        idiomas: ["Español"],
        fronteras: ["BOL", "BRA", "CHL", "PRY", "URY"],
        bandera: "https://flagcdn.com/w320/ar.png",
    },
    {
        nombre_comun: "Brasil",
        nombre_oficial: "República Federativa de Brasil",
        poblacion: 212559409,
        region: "América",
        capital: "Brasilia",
        moneda: "Real brasileño (BRL)",
        idiomas: ["Portugués"],
        fronteras: [
            "ARG",
            "BOL",
            "COL",
            "GUY",
            "PRY",
            "PER",
            "SUR",
            "URY",
            "VEN",
        ],
        bandera: "https://flagcdn.com/w320/br.png",
    },
    {
        nombre_comun: "México",
        nombre_oficial: "Estados Unidos Mexicanos",
        poblacion: 128932752,
        region: "América",
        capital: "Ciudad de México",
        moneda: "Peso mexicano (MXN)",
        idiomas: ["Español"],
        fronteras: ["BLZ", "GTM", "USA"],
        bandera: "https://flagcdn.com/w320/mx.png",
    },
    {
        nombre_comun: "Colombia",
        nombre_oficial: "República de Colombia",
        poblacion: 50882891,
        region: "América",
        capital: "Bogotá",
        moneda: "Peso colombiano (COP)",
        idiomas: ["Español"],
        fronteras: ["BRA", "ECU", "PAN", "PER", "VEN"],
        bandera: "https://flagcdn.com/w320/co.png",
    },
    {
        nombre_comun: "Alemania",
        nombre_oficial: "República Federal de Alemania",
        poblacion: 83240525,
        region: "Europa",
        capital: "Berlín",
        moneda: "Euro (EUR)",
        idiomas: ["Alemán"],
        fronteras: [
            "AUT",
            "BEL",
            "CHE",
            "CZE",
            "DNK",
            "FRA",
            "LUX",
            "NLD",
            "POL",
        ],
        bandera: "https://flagcdn.com/w320/de.png",
    },
    {
        nombre_comun: "España",
        nombre_oficial: "Reino de España",
        poblacion: 47351189,
        region: "Europa",
        capital: "Madrid",
        moneda: "Euro (EUR)",
        idiomas: ["Español", "Catalán", "Gallego", "Vasco"],
        fronteras: ["AND", "FRA", "GIB", "PRT", "MAR"],
        bandera: "https://flagcdn.com/w320/es.png",
    },
    {
        nombre_comun: "Francia",
        nombre_oficial: "República Francesa",
        poblacion: 67391582,
        region: "Europa",
        capital: "París",
        moneda: "Euro (EUR)",
        idiomas: ["Francés"],
        fronteras: ["AND", "BEL", "DEU", "ESP", "ITA", "LUX", "MCO", "CHE"],
        bandera: "https://flagcdn.com/w320/fr.png",
    },
    {
        nombre_comun: "Italia",
        nombre_oficial: "República Italiana",
        poblacion: 60359546,
        region: "Europa",
        capital: "Roma",
        moneda: "Euro (EUR)",
        idiomas: ["Italiano"],
        fronteras: ["AUT", "CHE", "FRA", "SMR", "SVN", "VAT"],
        bandera: "https://flagcdn.com/w320/it.png",
    },
    {
        nombre_comun: "Rusia",
        nombre_oficial: "Federación de Rusia",
        poblacion: 144104080,
        region: "Europa",
        capital: "Moscú",
        moneda: "Rublo ruso (RUB)",
        idiomas: ["Ruso"],
        fronteras: [
            "AZE",
            "BLR",
            "CHN",
            "EST",
            "FIN",
            "GEO",
            "KAZ",
            "PRK",
            "LVA",
            "LTU",
            "MNG",
            "NOR",
            "POL",
            "UKR",
        ],
        bandera: "https://flagcdn.com/w320/ru.png",
    },
    {
        nombre_comun: "China",
        nombre_oficial: "República Popular China",
        poblacion: 1402112000,
        region: "Asia",
        capital: "Pekín",
        moneda: "Yuan chino (CNY)",
        idiomas: ["Chino"],
        fronteras: [
            "AFG",
            "BTN",
            "MMR",
            "IND",
            "KAZ",
            "PRK",
            "KGZ",
            "LAO",
            "MNG",
            "NPL",
            "PAK",
            "RUS",
            "TAJ",
            "VNM",
        ],
        bandera: "https://flagcdn.com/w320/cn.png",
    },
    {
        nombre_comun: "India",
        nombre_oficial: "República de la India",
        poblacion: 1380004385,
        region: "Asia",
        capital: "Nueva Delhi",
        moneda: "Rupia india (INR)",
        idiomas: ["Hindi", "Inglés"],
        fronteras: ["AFG", "BGD", "BTN", "MMR", "CHN", "NPL", "PAK"],
        bandera: "https://flagcdn.com/w320/in.png",
    },
    {
        nombre_comun: "Japón",
        nombre_oficial: "Estado de Japón",
        poblacion: 125836021,
        region: "Asia",
        capital: "Tokio",
        moneda: "Yen japonés (JPY)",
        idiomas: ["Japonés"],
        fronteras: [],
        bandera: "https://flagcdn.com/w320/jp.png",
    },
    {
        nombre_comun: "Indonesia",
        nombre_oficial: "República de Indonesia",
        poblacion: 273523621,
        region: "Asia",
        capital: "Yakarta",
        moneda: "Rupia indonesia (IDR)",
        idiomas: ["Indonesio"],
        fronteras: ["MYS", "PNG", "TLS"],
        bandera: "https://flagcdn.com/w320/id.png",
    },
    {
        nombre_comun: "Egipto",
        nombre_oficial: "República Árabe de Egipto",
        poblacion: 102334000,
        region: "África",
        capital: "El Cairo",
        moneda: "Libra egipcia (EGP)",
        idiomas: ["Árabe"],
        fronteras: ["ISR", "LBY", "SDN"],
        bandera: "https://flagcdn.com/w320/eg.png",
    },
    {
        nombre_comun: "Nigeria",
        nombre_oficial: "República Federal de Nigeria",
        poblacion: 206139587,
        region: "África",
        capital: "Abuya",
        moneda: "Naira (NGN)",
        idiomas: ["Inglés", "Hausa", "Yoruba", "Igbo"],
        fronteras: ["BEN", "CMR", "NER", "TCD"],
        bandera: "https://flagcdn.com/w320/ng.png",
    },
    {
        nombre_comun: "Sudáfrica",
        nombre_oficial: "República de Sudáfrica",
        poblacion: 59308690,
        region: "África",
        capital: "Pretoria",
        moneda: "Rand sudafricano (ZAR)",
        idiomas: ["Afrikáans", "Inglés", "Zulú", "Xhosa"],
        fronteras: ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"],
        bandera: "https://flagcdn.com/w320/za.png",
    },
    {
        nombre_comun: "Australia",
        nombre_oficial: "Mancomunidad de Australia",
        poblacion: 25499884,
        region: "Oceanía",
        capital: "Canberra",
        moneda: "Dólar australiano (AUD)",
        idiomas: ["Inglés"],
        fronteras: [],
        bandera: "https://flagcdn.com/w320/au.png",
    },
    {
        nombre_comun: "Nueva Zelanda",
        nombre_oficial: "Nueva Zelanda",
        poblacion: 5084300,
        region: "Oceanía",
        capital: "Wellington",
        moneda: "Dólar neozelandés (NZD)",
        idiomas: ["Inglés", "Maorí"],
        fronteras: [],
        bandera: "https://flagcdn.com/w320/nz.png",
    },
];
